### ISSUE TITLE
about tf.app.flags and argparse

### ISSUE THREAD

**Issue by EigenvectorOfFate** [nikhil-dce/Transforming-Autoencoder-TF#1]
Thank you ! You did a great job.
I was a beginner who has just started learning to Python, TensorFlow and Capsule. I read the code and was confused about the tf.app.flags and argparse, they seem to do the same job, but why you used both of them. Do you have some particular reason to use both of them?

**Comment by nikhil-dce** [comment]
@EigenvectorOfFate Thanks for pointing that out.
This project is actually a part of a larger project which relies heavily on tf.app.FLAGS. To avoid confusion, I have removed argparser from this repository.
